import fs from 'node:fs';import path from 'node:path';import{fileURLToPath}from'node:url';import{marked}from'./vendor/marked.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),src=path.join(root,'docs/en'),out=path.join(root,'dist/en/reports'),original=path.join(root,'dist/reports');fs.mkdirSync(out,{recursive:true});
const names=fs.readdirSync(original).filter(x=>x.endsWith('.md'));const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
for(const name of names){if(!fs.existsSync(path.join(src,name)))throw Error('Missing English report: '+name);const md=fs.readFileSync(path.join(src,name),'utf8');let body=marked.parse(md);
body=body.replace(/<a href="([^"]+)"([^>]*)>([\s\S]*?)<\/a>/g,(all,url,extra,label)=>{if(/^(https?:|mailto:|#)/.test(url))return all;const base=path.basename(url.replace(/^sandbox:/,''));if(names.includes(base))return `<a href="${esc(base.replace(/\.md$/,'.html'))}">${label}</a>`;if(fs.existsSync(path.join(original,base)))return `<a href="../../reports/${esc(base)}">${label}</a>`;return `<span>${label}</span>`;});
body=body.replace(/<img src="([^"]+)"([^>]*)>/g,(all,url,extra)=>{const base=path.basename(url.replace(/^sandbox:/,''));return fs.existsSync(path.join(original,base))?`<img src="../../reports/${esc(base)}"${extra}>`:'';});body=body.replaceAll('<table>','<div class="table-wrap"><table>').replaceAll('</table>','</table></div>');
const title=(md.match(/^# (.+)$/m)||[])[1]||name,historical=!['PROJECT_REPORT.md','REPRODUCIBILITY.md','SOURCES.md'].includes(name);
const note=`<p class="translation-note">English reading edition. ${historical?'This is a historical stage report; the <a href="PROJECT_REPORT.html">final project report</a> takes precedence for corrected parameters and release-wide conclusions. ':''}Original figure and video labels, numerical files and programs are retained. <a href="../../reports/${name.replace(/\.md$/,'.html')}">Russian source</a>.</p>`;
fs.writeFileSync(path.join(out,name.replace(/\.md$/,'.html')),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} — Prostranstva</title><link rel="stylesheet" href="../../assets/style.css"></head><body><article class="document"><a href="../materials.html">← Project catalogue</a>${note}${body}<hr><a href="${name}" download>English Markdown</a></article></body></html>`);fs.copyFileSync(path.join(src,name),path.join(out,name));}console.log(`Rendered ${names.length} English reports`);
